### ISSUE TITLE
Quel est le projet ?

### ISSUE THREAD

**Issue by bertho-zero** [Oli8/dApp-starter#1]
Salut,

Je vois que tu t’intéresses aussi à la blockchain, c'est un projet uniquement pour tester ou t'as une réelle idée derrière la tête ?

**Comment by Oli8** [comment]
Hello,

Avec un collègue on a commencé un projet de certification de qualité de vie au travail pas trop serieux dont la base a servi à ce répo qui vise pas de projets en particuliers mais qui servira de boilerplate pour de futurs dapp :)
